### ISSUE TITLE
how to integrate websocket with redux?

### ISSUE THREAD

**Issue by hyzhak** [fire-marshal/fire-marshal#52]
We have sources of data in a way of web sockets
And we want to consume this data to Redux state
so our main web app could take new data and reflect it in a right way.
But here comes some questions about pipeline and lifecycle:
- what is the best way to start and stop web socket module?
For example when we not using chat we don't need flow of incoming messages
but we could need this flow in few components. So it could make sense to
trigger on/off module depends on visible components. the Stateful components
because stateless component doesn't care much about this state.
So each stateful component could have `PubSubModule.start()` and
`PubSubModule.stop()`.
Another alternative - unbind PubSub Modules from component but bind on state updat
it could be current visible page, login/logout user and etc.
So PubSub Module subscribe on state update, and check whether it should start/stop
- Update request to server
For example our app gets updates depends on our location and user's actions,
and sure when user walks her location could change so we should update query
of subscribed data.
There are few alternatives:
1) call `PubSubModule.update(new_params)` directly from component
2) subscribe on Redux state change and update when we need it.
But we should remember previous request and send "diff" only --
in case of new data.
# Challenges
- optimize Redux state subscription. We still can have problem because
we can't subscribe for specific option. But should react on ant tiny piece update.
Partly Solution: use libs like `reselect`
which store intermediate state tree result so we won't need to go deep
and extract everything
we have few alternatives here, to how could we get state for requests:
# Architecture
- Should it be middleware?
- Is it another form of UI component?

# Websocket as Middleware

it seems middleware is the best way to integrate websockets.

# So lets consider Options
- [ ] [Using socket.io in React-Redux app to handle real-time data.](https://medium.com/@gethylgeorge/using-socket-io-in-react-redux-app-to-handle-real-time-data-c0e734297795)
- [ ] https://github.com/laumair/resocket
- [ ] https://github.com/notgiorgi/redux-websocket-middleware
- [ ] and [many others](https://github.com/markerikson/redux-ecosystem-links/blob/master/middleware-sockets-adapters.md#websockets)

**Comment by hyzhak** [comment]
based on post [Redux WebSocket Integration](https://medium.com/@mark.erikson/out-of-curiosity-why-not-implement-your-socket-handling-logic-as-an-actual-redux-middleware-4d1ec0594fd2)
# Client Redux Middleware
- subscribe on all ws message, extract type and payload from it and match type to existing actions types. If it matches dispatch the action with payload
- on special *emit* actions emit ws event to server (so server could hold your state and fire needed events back to you)

# Server Side
- Q: how to store user's state?
- Q: how to use user's state and subscribe to something else and emit ws back to client?
- Q: isn't it make _fat_ server?

**Comment by hyzhak** [comment]
base on https://github.com/notgiorgi/redux-websocket-middleware

- create connection manager (https://github.com/notgiorgi/redux-websocket-middleware/blob/master/src/lib/ConnectionManager.js)
  - uses redux store to emit events on open, close, error, receive message events (https://github.com/notgiorgi/redux-websocket-middleware/blob/master/src/actions.js)
  - queue of messages
  - use native WebSocket

**Comment by hyzhak** [comment]
based on https://github.com/cape-io/cape-redux-socket/
- [cookie middleware](https://github.com/cape-io/cape-redux-socket/blob/master/src/cookie.js)

**Comment by hyzhak** [comment]
the most popular https://github.com/itaylor/redux-socket.io and one of the simplest solution.

**Comment by hyzhak** [comment]
## TODO: should try to implement server side logic
- receives users data (input)
- store data (MongoDB)
- react on new data (subscribe to something)
- gets data from something 
- send messages back to user
_in other words it is simplified version of user but on server side_

**Comment by hyzhak** [comment]
## Few types of client state
### consistent
- important only the last state (doesn't care about history) we don't need queue here
- example: user's location, watching streaming data
- server agent could restart and ask this state again from db (?) or client (?)
### coherent
- important all history (queue)
- example: user's messages
